version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
    # - $DB_PORT:$DB_PORT
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  fiverr_be:
    depends_on:
      - mysql_db
    build: .
    container_name: fiverr_be
    env_file: .env
    environment:
      - DATABASE_URL=$DB_URL_DOCKER
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=saltair.site
      - LETSENCRYPT_HOST=saltair.site
      - LETSENCRYPT_EMAIL=duongngochung13@gmail.com
    ports:
      - "3030:80"
    networks:
      - node-network

volumes:
  mysql_db:
    driver: local

networks:
  node-network:
  

